### ISSUE TITLE
Expand documentation

### ISSUE THREAD

**Issue by leeper** [IQSS/dataverse-client-r#1]
- [x] Vignette demonstrating data access and download
- [x] Package documentation
  - [x] Native API
  - [x] Search API. This is quite complicated and possibly installation-dependent (see https://github.com/IQSS/dataverse/issues/2558). This should be accommodated, for the time being, on the documentation level only. It can be expanded later.
  - [x] Data access
  - [x] Data deposit/SWORD API
- [x] README examples

**Comment by leeper** [comment]
vignettes were added here: https://github.com/IQSS/dataverse-client-r/commit/a16c0cdc7a95b86a9147305506b413324f832b5a but aren't finished yet

**Comment by brownaa** [comment]
I'm open to forking this and adding documentation for reading data into R.  However, I can't make it work myself.  The documentation in the latest commit gives errors and I've tried to debug the issue to no avail.

**Comment by brownaa** [comment]
I figured out a process for working with CSV and other text-based files.  I don't know how to generalize this to all file types yet though.

**Comment by pdurbin** [comment]
@brownaa maybe for now you could attach your script or whatever to this issue. You might need to change the extension to ".txt".
