### ISSUE TITLE
Add and replace APIs

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-r#10]
As I mentioned at https://groups.google.com/d/msg/dataverse-community/8WTs3wYF6dc/AzPOxzRKFwAJ there are two new APIs having to do with adding and replacing files that we expect to ship with Dataverse 4.6.1. They address this issue: https://github.com/IQSS/dataverse/issues/1612

Once the code and docs are final, I'll leave a comment on this issue but if anyone wants to kick the tires on the new APIs now, please follow the link to the Google Group above! 😄

**Comment by leeper** [comment]
Nice. I'll incorporate this.
