### ISSUE TITLE
CRAN 0.3.11

### ISSUE THREAD

**Issue by kuriwaki** [IQSS/dataverse-client-r#119]
I plan to submit a new version to CRAN in the next few days. This will mostly address bugs and minor fixes related to upload.

In dev,

- [x] #116 (thanks @Danny-dK)
- [x] #115 
- [x] Check and submit to CRAN
- [x] Merge to master

EDIT: for later:

- #82 
- #20 - perhaps outdated
- #23 will try

**Comment by kuriwaki** [comment]
@Danny-dK please feel free to send me your name / contact if you'd like to be added as contributor in [DESCRIPTION](https://github.com/IQSS/dataverse-client-r/blob/master/DESCRIPTION) for this version

**Comment by Danny-dK** [comment]
@kuriwaki  Thanks, but no need. My contributions have been very minimal (not worthy of any mention ;) )

**Comment by kuriwaki** [comment]
The longstanding data upload functions have not been fixed yet, but there are some other important bugfixes dev so I'll start the submission with what we have so far. I left a note in the README about the data upload issues.

**Comment by kuriwaki** [comment]
It's accepted, so will merge. @Danny-dK thanks again for your help. I will try to think of ways to resolve the create_dataverse + add_dataset issues, but and any other PRs will be awesome as well.
