### ISSUE TITLE
release of haven 2.5.0

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#120]
A [new version of haven was released three days ago](https://cloud.r-project.org/web/packages/haven/news/news.html).  ([GitHub version of release notes](https://github.com/tidyverse/haven/releases/tag/v2.5.0))

@kuriwaki, I don't think any of these changes will cause problems with dataverse, but I wanted to start an issue in case anything suspicious pops up.  If everything is quiet, I think this issue can be closed in a week or so.

**Comment by kuriwaki** [comment]
Have had no problems so far!
