### ISSUE TITLE
rename default branch to "main"

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#126]
@kuriwaki, after things are accepted on CRAN, do you mind if I rename the default branch?  There are some git commands you can run locally, but honestly it's almost easier to delete and reclone your local copy.

https://ouhscbbmc.github.io/data-science-practices-1/git.html?q=master#main-vs-master-branch

**Comment by pdurbin** [comment]
@kuriwaki you weren't part of https://github.com/orgs/IQSS/teams/dataverse-client-r-admin but I just added you. (You were part of the "write" team.)

**Comment by kuriwaki** [comment]
Thanks @pdurbin. That worked and now the branch is renamed. I will fix the reference in our workflow from "master" to "main" as well.
