### ISSUE TITLE
Problem downloading larger files

### ISSUE THREAD

**Issue by JBGruber** [IQSS/dataverse-client-r#128]
- [x] a suggested code or documentation change, improvement to the code, or feature request

```R
library(dataverse)

Sys.setenv("DATAVERSE_SERVER" = "dataverse.harvard.edu")
ds <- get_dataset("doi:10.7910/DVN/ZY3RV7")

DE <- which(ds$files$label == "ParlEE_DE_plenary_speeches.csv")

get_file_by_id(ds$files$id[DE], 
               dataset = "doi:10.7910/DVN/ZY3RV7")
```

# The problem

When downloading files, they are loaded into memory before being written to disk. This is no issue with smaller files, but I keep running into issues when I try to download larger ones, such as the 1.8GB csv file from [this data set](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FZY3RV7&version=&q=&fileTypeGroupFacet=&fileAccess=&fileSortField=size&tagPresort=false). The code above is not always throwing an error, only when running on a machine with limited resources or a slow internet connection.

What I would suggest is to allow the user to download the files in a different way. A simple argument like `return_url`, for example, could just do that and skip the download. The user could then use an external function like `curl::curl_download` or copy the link to an external application. I have a pull request ready, if there is interest.

**Comment by kuriwaki** [comment]
I'm definitely intrigued to try out a PR. Trouble with large files has been a clear issue.
