### ISSUE TITLE
Document (and maybe implement) ability to create a new version of an existing dataset

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-r#13]
Over at https://github.com/IQSS/IQSSdevtools/issues/1 @christophergandrud just asked if it's possible to create a new version of an existing dataset using dataverse-client-r. It's definitely possible from the Dataverse API side, but I wasn't able to quickly figure out if it's supported by this client or not.

**Comment by leeper** [comment]
This is possible already using the `publish_dataset()` function. Let me know if I can make this clearer (I'm sure it will be shortly once I finish documenting some of the native API features).

**Comment by christophergandrud** [comment]
Awesome. Thanks @leeper

**Comment by pdurbin** [comment]
@leeper nice chatting with you about this in person today! I'm glad to hear you're able to wrangle the JSON format easily enough.
