### ISSUE TITLE
Add function to recalculate UNF

### ISSUE THREAD

**Issue by leeper** [IQSS/dataverse-client-r#15]
Recalculate the UNF value of a dataset version, if it’s missing, by supplying the dataset version database id:

```curl
POST http://$SERVER/api/admin/datasets/integrity/{datasetVersionId}/fixmissingunf
```

**Comment by pdurbin** [comment]
@leeper please note that for security reasons, the "admin" API is usually blocked on productions installations of Dataverse: http://guides.dataverse.org/en/4.6.2/installation/config.html#blocking-api-endpoints

**Comment by leeper** [comment]
Makes sense. I am trying to implement stuff for most of the API even though it won't be available to package users.

**Comment by pdurbin** [comment]
@leeper great! Don't let me discourage you! 😄
