### ISSUE TITLE
Add git repo archiving example

### ISSUE THREAD

**Issue by leeper** [IQSS/dataverse-client-r#16]
Add an example (based upon https://github.com/IQSS/dataverse/issues/2739) showing how to archive a git repo using the SWORD API.

**Comment by pdurbin** [comment]
I'd feel remiss if I didn't point out that GitHub integration is also being tracked at https://github.com/IQSS/dataverse/issues/5372

**Comment by kuriwaki** [comment]
We can revisit this once the SWORD/upload related issues are fixed.
