### ISSUE TITLE
Test with jenkins.dataverse.org 

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-client-r#22]
Over at https://github.com/IQSS/dataverse/issues/5725 we're talking about a new continous integration service for the Dataverse community hosted by UNC (thanks!) at https://jenkins.dataverse.org

We should add a job for this client library, dataverse-client-r.

**Comment by pdurbin** [comment]
@monogan @maxheld83 (possible contributors from #21) I just set up a "push" webhook to https://jenkins.dataverse.org/github-webhook/

@donsizemore and I discussed this at http://irclog.iq.harvard.edu/dataverse/2019-06-04#i_96026

**Comment by kuriwaki** [comment]
The live testing functionality we came up with in #40 seems ok for now. Also, https://jenkins.dataverse.org is down for me.

**Comment by pdurbin** [comment]
> Also, https://jenkins.dataverse.org is down for me.

I'm cool with the plan in #40 but wanted to mention the our Jenkins instance is limited to certain IP addresses and ranges. If you need access, please email support@dataverse.org.
