### ISSUE TITLE
Fix Travis problems (2019 Oct)

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#25]
It looks like Travis [has not passed in two years](https://travis-ci.org/IQSS/dataverse-client-r/builds?utm_medium=notification&utm_source=github_status) (ie, [Oct 2017 was the last full success](https://travis-ci.org/IQSS/dataverse-client-r/builds/286026865?utm_medium=notification&utm_source=github_status)).  

Things pass on my local machine (which is Ubuntu, like Travis), so I think the problem likely lies with the travis config, rather than the R machinery.  I'll try to 
- [x] simplify the config until it passes, then
- [x] re-add the Travis matrix cells/conditions so it passes, but still replicates the intent of the current config

**Comment by wibeasley** [comment]
Does anyone strongly believe the 7.3 OSX build should continue?  What about Ubuntu 12.04 LTE (ie, 'precise')?

I think these older releases could be the cause of the travis fails.  The 7.3 tool chain is [no longer checked on CRAN](https://cran.r-project.org/web/checks/check_flavors.html#r-release-osx-x86_64) (only 8.3).  Similarly, Ubuntu 12.04 was released 7.5 years ago, and was [EOLed 2.5 years ago](https://wiki.ubuntu.com/Releases).

**Comment by pdurbin** [comment]
@wibeasley I'd say you should kill those builds for older operating systems if they're causing you trouble. If people complain, we can always attempt to add them back in later.

**Comment by wibeasley** [comment]
@pdurbin sounds good.  [The config now has](https://github.com/IQSS/dataverse-client-r/blob/master/.travis.yml) the two most recent Ubuntu versions, plus the 8.2 toolchain on OSX.  And I agree that if people express the need to check additional versions, we can easily evaluate the tradeoffs of resurrecting those checks.

I think this is what you meant, but this controls just the *checking* on the master branch.  CRAN handles the [checks and binary builds on CRAN](https://cran.r-project.org/web/checks/check_flavors.html).
