### ISSUE TITLE
fq for dataverse_search is broken

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse-client-r#37]
Please specify whether your issue is about:

 - [x] a possible bug
 - [ ] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

Put your code here:

```R
## load package
library("dataverse")

## code goes here
datasets <- dataverse_search("*", fq = "dateSort:[2018-01-01T00:00:00Z+TO+2019-01-01T00:00:00Z]", type="dataset", key = "",  server = "dataverse.harvard.edu"))


## session info for your system
sessionInfo()
```

I'm proposing a fix for this in #36

**Comment by wibeasley** [comment]
@adam3smith, I believe this can this be closed now.  Reopen it if I'm overlooking something.
