### ISSUE TITLE
package scaffolding

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#38]
As I've [expressed](https://groups.google.com/d/msg/dataverse-community/j-cGlnpKs14/pCTdOoXJAwAJ) with a few tweaks:
> I'd (like to) modify some of the package's structure to more closely resemble the approach described in Hadley's [R Packages book](http://r-pkgs.had.co.nz/) (and the [tidyverse style guide](https://style.tidyverse.org/)).  The first reason is because I think it's a good approach and has worked well for me in the past.  A second reason is that this approach is documented better and more coherently than any other approach --therefore it will be easier for someone else to modify or become maintainer in the future.
>
>But this won't be a major overhaul.  Most of the important elements of the existing package follow this book's approach.

The changes come in two sets: the little guys that come *before* adding a test suite (issues #4 & #29) and those that come *after* the test suite (which includes some of the recently accumulating issues like #33, #35, & #37).

### Before test suite
- [x] Rproj
- [x] update Roxygen
- [x] updates to .Rbuildignore and .gitignore files.
- [x] move daily development off the master and to the dev branch
- [x] update [person entries](https://journal.r-project.org/archive/2012/RJ-2012-009/RJ-2012-009.pdf) in [DESCRIPTION](https://codecov.io/github/IQSS/dataverse-client-r?branch=master) file
- [x] [semantic versioning](http://r-pkgs.had.co.nz/description.html#version) for dev versions (*e.g.*, x.x.x.9001)
- [x] remove date from [DESCRIPTION](https://codecov.io/github/IQSS/dataverse-client-r?branch=master) file
- [x] (re)connect [codecov](https://codecov.io/github/IQSS/dataverse-client-r?branch=master) which currently reads 0%. (@pdurbin, as an admin of this GitHub org, you'll probably see my request for additional permissions granted to Codecov.  I requested it only for this single public repo.)

    [![image](https://user-images.githubusercontent.com/1372890/71646866-96e02580-2cbb-11ea-917d-b72aa2fabd7e.png)](https://codecov.io/github/IQSS/dataverse-client-r?branch=master) (click the image for the live staus)

### After test suite and functional changes
- [x] [pkgdown](https://pkgdown.r-lib.org/) site #72
- [x] comply with some of [lintr](https://github.com/jimhester/lintr)'s flags. #41
- [ ] Maybe add to CRAN's [Reproducible Research view](https://cran.r-project.org/web/views/ReproducibleResearch.html)

I'm flexible if anyone has other ideas.

**Comment by pdurbin** [comment]
> my request for additional permissions granted to Codecov

Yes, you may have seen that @whorka approved this request earlier today. Thanks for working on the tests! 🎉

**Comment by kuriwaki** [comment]
This tidyverse style package scaffolding seems largely complete. The issues in the create_* functions will get dealt with using the same scaffolding. Thanks @wibeasley !!
