### ISSUE TITLE
Thank you, Thomas Leeper

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#42]
@leeper, thanks for developing such a stable and well-designed package.  Digging into it during the past week, I'm even more appreciative of its design and consistency.  And you left a good roadmap of what the package needs next (eg, #4 & #16), which has helped the transition  It's been fun learning about it and gaining some new tools in my toolbox along the way.

(*To those on the repo's watchlist, I promise I won't bend the purpose of GitHub issues too frequently.  But I think @leeper deserves the additional recognition.*)

ref #21

**Comment by leeper** [comment]
Hey, thanks. That’s really nice of you to say!
