### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by eblondel** [IQSS/dataverse-client-r#57]
Thank you for this package. Do you plan any additional release in CRAN soon to publish fixes and enhancements since latest release (2017)? Thanks in advance

**Comment by wibeasley** [comment]
@eblondel, I do plan to release to CRAN again.  I was hoping to have added more test coverage before I do.  But I can be convinced otherwise if you need it on CRAN soon.

List of functions to cover: https://github.com/IQSS/dataverse-client-r/issues/4#issuecomment-570818387

**Comment by wibeasley** [comment]
@eblondel, I do plan to release to CRAN again.  I was hoping to have added more test coverage before I do.  But I can be convinced otherwise if you need it on CRAN soon.

List of functions to cover: https://github.com/IQSS/dataverse-client-r/issues/4#issuecomment-570818387
