### ISSUE TITLE
restore testing dataverse

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#65]
Somehow the testing dataverse contents were deleted.

I'll 
- [x] restore the file contents
- [x] update the addresses & dois in the testing code
- [ ] create a second user account that has read-only privileges to the dataverse

https://demo.dataverse.org/dataverse/dataverse-client-r

**Comment by kuriwaki** [comment]
@pdurbin  Once a dataverse is published on demo.dataverse.org, I hope it won't get deleted by maintenance -- even if there is no action on it?

**Comment by pdurbin** [comment]
Hi, my understanding is that all data on demo.dataverse.org is deleted periodically unless it it marked to be skipped. Let's ask @djbrooke and @kcondon about the details.

**Comment by djbrooke** [comment]
@pdurbin thanks for the ping. Yeah, that's my understanding as well. Apologies if this created extra work here.

If the content can be re-created, let me know and I can work with @kcondon to understand more and get it on the not-to-be-deleted list.

**Comment by kcondon** [comment]
@djbrooke Yes, the assumption, after originally checking with the support and curation team, is that demo is typically used for short term exploration of functionality and there was no guarantee of persistence past a certain point. We have limited storage space on that machine so we clear it out regularly. It was being cleared on a 30 day basis but will check whether that had been moved up to weekly. Maybe the use cases for this service has changed? I know we'd started encouraging people writing to the API to use that box to develop or verify scripts so maybe that takes longer? @pdurbin?

**Comment by djbrooke** [comment]
Thanks @kcondon for the details!

@wibeasley - if you have some datasets or a dataverse that you want us to keep around, just let us know and we'll get it added to that exclusion list above. Sorry again for the inconvenience.

**Comment by kuriwaki** [comment]
@kcondon  @djbrooke  We created https://demo.dataverse.org/dataverse/dataverse-client-r and would like for any datasets in this dataverse to be kept around.  No worries about any previous datasets -- this is a new one created last week.

The use case is for this dataverse to be a permanent link for our continuous integration tests as well as example code that will be widely featured on the package website. It does need to be on demo.dataverse.org.  In fact, it might be more closer to real example if it had a DOI. (I wonder if what you highlighted about the demo message is the reason the DOI URLs on the demo Dataverse are not published).

**Comment by pdurbin** [comment]
All this sounds great. I just wanted to mentioned that @wibeasley and I had a video chat yesterday and touched on this. We very briefly went down the road of plugging dataverse-client-r as perhaps a last step in our normal "spin up an EC2 instance and test with Jenkins" process but for now probably easier to use the demo server. I said I don't think anyone will mind if the data storage requirements are small and he showed me that the test files are only a few kilobytes in size so I think we'll be fine. Thanks all for helping making regular automated testing of this code a reality!

**Comment by kcondon** [comment]
@kuriwaki All set, the two datasets have been added to the do not delete. Will pursue larger issue on use cases w/ @djbrooke separately.

**Comment by kuriwaki** [comment]
Thanks all - closing this, as the demo Dataverse seems stable now: https://demo.dataverse.org/dataverse/dataverse-client-r
