### ISSUE TITLE
Test for expected data rectangles and file contents

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#70]
As part of the test suite (#4), the retrieved data & files should be compared to their expected values/file/data.  Some of the options are:
- [x] the original data file (compared as text)  --this is the most portable across client libraries, like [pyDataverse](https://github.com/gdcc/pyDataverse) and [dataverse-client-python](https://github.com/IQSS/dataverse-client-python).  See #29
- [ ] the tsv from the ingested tab (maybe compared as text) 
- [x] the data.frame converted from the ingested tab (maybe compared as an rds)

**Comment by kuriwaki** [comment]
What's the difference between the second and third items? Once a tabular datafile is read into R, it's already a dataframe.

If we want to go for extensive tests, I think we want tests for:

- [ ]  ingested datafiles read in in their ingested (tab plain text) form
- [ ] ingested datafiles read in their original form (which may be csv, dta, sav, xlsx - see [supported formats](https://guides.dataverse.org/en/latest/user/tabulardataingest/supportedformats.html)). 
- [ ] non -ingested datafiles (e.g. a rds file [nlsw_rds-export.rds](https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/PPIAXE/SUCFNI)) read in their original form

**Comment by kuriwaki** [comment]
The above commits give decent tests for rds and rda.
