### ISSUE TITLE
Parsing error for some large Stata files

### ISSUE THREAD

**Issue by kuriwaki** [IQSS/dataverse-client-r#80]
The download and parsing for [this](https://doi.org/10.7910/DVN/XFXJVY/GQMQLG) large file errors out though I'm not sure why. 

The `get_file` stage succeeds; it only fails in the parsing/reading stage. It is a large Stata dta file, and we call it as not ingested even though on the GUI it appears to be ingested.

```r
out <- get_dataframe_by_doi("https://doi.org/10.7910/DVN/XFXJVY/GQMQLG")
# Error in get_dataframe_by_id(fileid = filedoi, .f = .f, original = original,  : 
#   read-in function was left NULL, but the target file is not ingested or you asked for 
# the original version. Please supply a .f argument.

out <- get_dataframe_by_doi("https://doi.org/10.7910/DVN/XFXJVY/GQMQLG",  original = TRUE, .f = haven::read_dta)
# Error in df_parse_dta_file(spec, encoding, cols_skip, n_max, 
# skip, name_repair = .name_repair) : 
#   Failed to parse /private/var/folders/58/bg0qcxrs7s7fgf3x_qlj8njw0000gn/T/Rtmpi5QTMl/foo128340268bdd: 
# This version $ of the file format is not supported.

# the raw version works.
out <- get_file_by_doi("https://doi.org/10.7910/DVN/XFXJVY/GQMQLG")
class(out)
# [1] "raw"
```

**Comment by wibeasley** [comment]
So is this a haven problem?  Can haven convert it, independently from the dataverse package?

**Comment by kuriwaki** [comment]
It's relevant for `dataverse`  in the sense that this was not a proble before 0.3.0 (see before and after as separate reprex's below). I think it might be something to do with the defaults in `httr::GET` -- maybe they were inadvertently changed.

``` r
# Version BEFORE 0.3.0 but after we patch fixed some get_file errors 
# remotes::install_github("IQSS/dataverse-client-r", 
#                         ref = "0b3d67c70cb90dbaf499d65c59972512f4a8eb7a")

library(dataverse)
library(haven)

packageVersion("dataverse")
#> [1] '0.2.1.9001'

out <- get_file(file = "CCES14_Common_Content_Validated.tab", 
                dataset  = "10.7910/DVN/XFXJVY", 
                server = "dataverse.harvard.edu")

# render the raw binary -- should be a tibble
class(read_dta(out))
#> [1] "tbl_df"     "tbl"        "data.frame"
```


``` r
# Current CRAN Version

library(dataverse)
library(haven)

packageVersion("dataverse")
#> [1] '0.3.0'

out <- get_file(file = "CCES14_Common_Content_Validated.tab", 
                dataset  = "10.7910/DVN/XFXJVY", 
                server = "dataverse.harvard.edu")

# render the raw binary -- should be a tibble
class(read_dta(out))
#> Error in df_parse_dta_raw(spec, encoding, cols_skip, n_max, skip, name_repair = .name_repair): Failed to parse file: This version of the file format is not supported.
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kuriwaki** [comment]
I've done a bit more testing by putting up various versions of the CCES data on a separate demo.dataverse.org account: https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2FV14QR6

I haven't found why this fails but it might be related to ingesting. Interestingly, subsets of the problematic data (2014 and 2016) _do_ work. I made 51 partitions of the data for each state and uploaded on to the above link.  They all ingested fine and I could read them via `get_dataframe_by_name` no problem. However, when I tried to upload the whole 2016 data again, demo.dataverse.org said it failed to ingest it and pushed it as an original .dta (see [here](demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/V14QR6/L1VRIU&version=4.0)). This is different from the original 2016 [dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910/DVN/GDF6Z0). 

I'll have to ask Dataverse folks for more details about their API in the new year.

**Comment by pdurbin** [comment]
@kuriwaki it looks like CCES16_Common_OUTPUT_Feb2018_VV.dta failed ingest. It's possibly due to the large size (546.7 MB).

In https://github.com/IQSS/dataverse/pull/8271 (not merged yet) we're proposing to give the research more information about upload limits and ingest limits. Right now it looks like this:

![146075895-7b84eb2b-b664-4077-8eb3-6a4e05ec166c](https://user-images.githubusercontent.com/21006/147950925-bf8e280e-7ae6-48aa-989e-56dc576b5233.png)

(These limits are arbitrary and random, by the way, but I hope you get the idea.)

You are welcome to leave feedback on that pull request. Thanks!

**Comment by pdurbin** [comment]
> It's possibly due to the large size (546.7 MB).

Me again. I tried it on demo and the size is allowed but I got a strange error:

> Tabular data ingest failed. Ingest failed to produce Summary Statistics and/or UNF signatures; /tmp/tempTabfile.9853244723487760894.tab (No such file or directory)

Here it is in context:

![Screen Shot 2022-01-03 at 1 32 29 PM](https://user-images.githubusercontent.com/21006/147966730-a5aa9bad-4610-4472-9fd2-937efed971d8.png)

**Comment by kuriwaki** [comment]
@pdurbin: great. If it's not failing because of size, that could be a hint to why we are having trouble reading in the original version, uploaded 2018 ([here](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/GDF6Z0/JPMOZZ&version=4.0)). For example, I think this is not a pure Stata file but instead a Stata file that is translated from a SPSS .sav file via StatTransfer or other software, which might explain the error. I'll look in.

Does the Harvard Dataverse file that I linked to ^ show any traces of ingest issues -- especially those that a similarly sized CCES 2012 ([here](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/HQEVPK/J0KBXB&version=9.0)) does not?

and thanks for mentioning the PR -- the updated error message would certainly be useful. As you probably know, the message I got in December read "ingest process has finished with errors. ...Ingested files: CCES16_Common_OUTPUT_Feb2018_VV.dta (Error)"

**Comment by kuriwaki** [comment]
Ok, I finally have an answer for this narrow issue. I believe it fails because the detection for [`is_ingested`](https://github.com/IQSS/dataverse-client-r/blob/4775a92360569adb6e693ad6db940f89530eeb8d/R/utils.R#L102-L116) is wrong. When `is_ingested` returns FALSE even though it is ingested, then we force nullify `format=original` which messes up the way we download the file. 

If we can rewrite is_ingested that would be great, but may take a while -- I posed the question in #113. 
Perhaps a quicker route for now is to change some defaults. For example, we might force `format=original` if we know that `original=TRUE` (`get_dataframe_*` defaults to `original=FALSE` now), so that we'd get the original regardless of the accuracy of `is_ingested`.

**Comment by kuriwaki** [comment]
This should be fixed in the new CRAN version now. The short answer is that by the particular CCES files we were dealing with seemed somewhat mal-ingested, in which the ingest did go through but it did not generate a metadata file, and we had been relying on the latter to detect. By changing to a less hacky-way in #113, we can now avoid this issue. 

Thanks @pdurbin. And @pdeshlab, thanks for the examples and let me know what you find with the new CRAN version.
