### ISSUE TITLE
CRAN Down

### ISSUE THREAD

**Issue by joeHickson** [IQSS/dataverse-client-r#83]
The cran dataverse package is no longer available for download
https://cran.r-project.org/web/packages/dataverse/index.html

**Comment by djbrooke** [comment]
Thanks @joeHickson for the report and @pdurbin for the ping. From a quick look, I think I see the issue. 

@wibeasley @kuriwaki - about a year ago, we added token expiration after a year, so it's likely that the token from https://github.com/IQSS/dataverse-client-r/blob/master/inst/constants.yml just needs to be re-created. Let me know if there's anything I can do to help with this.

**Comment by kuriwaki** [comment]
I thought this is about #77 so token expiration sounds right. Thank you @djbrooke. So you think I or @wibeasley can create a fresh token and replace the yaml?

**Comment by djbrooke** [comment]
Hey @kuriwaki -- based on the errors in https://cran-archive.r-project.org/web/checks/2021/2021-02-16_check_results_dataverse.html it seemed likely to me. I'd guess replacing the token and rerunning the tests would be a likely fix. I'm not sure if this resubmits to CRAN automatically or if there's some other step. 

If it's not the token expiration, it would at least allow us to rule something out. :)

**Comment by kuriwaki** [comment]
The `SSL certificate problem: certificate has expired ` error in your link only happens in  r-patched-solaris-x86, which is consistent with the issue I linked to (though even then I couldn't understand why that would happen in Solaris but not in all the linux/windows/mac OS they test on).

We would need to resubmit to the CRAN team through their form, so the earliest we can fix this is next week I think. 

It'd be great if we could test this before we resubmit so we can make sure it'll pass. I'm not the maintainer so it seems I cannot [use r-hub to test on Solaris](https://blog.r-hub.io/2020/05/14/checking-your-r-package-on-solaris/) easily.

**Comment by kuriwaki** [comment]
Separately, the error log reports a host of errors in previously unproblematic places, for other OS. It looks like there is a simple   mixup of the [two](https://demo.dataverse.org/dataverse/dataverse-client-r) of the Datasets in our test dataverse. Our tests use `contents[[1]]` to call a dataset, and maybe the order of the datasets returned in `get_dataverse()` changed underneath so we got the wrong one. 

https://github.com/IQSS/dataverse-client-r/blob/dec2cb1800548556badeb65bcb00b1671cd9e011/tests/testthat/tests-dataset_files.R#L7

That said, I'm not sure why this would suddenly happen, since we did not change the test data. Also, `devtools::check()` returns no errors on my local.

**Comment by kuriwaki** [comment]
I implemented a quick lookup in the tests to avoid the [[1]] / [[2]] ambiguity (09eb25a). This is on top of @wibeasley's edits early on to avoid the expiration issue (ff5a80e15df512e15b787dae8b2ee27490cf63eb).

I ran `devtools::check()` locally and I get no errors or warnings. Just one NOTE that says "`Package suggested but not available for checking: ‘UNF’`"

**Comment by kuriwaki** [comment]
Update here: The 0.3.5 resubmission passed CRAN's auto-checks today and is now under manual inspection.

**Comment by kuriwaki** [comment]
It's back up as 0.3.7 with a couple of improvements. Thanks @wibeasley!

**Comment by wibeasley** [comment]
The R-hub problems aren't not really related to CRAN, but needed to be solved first.
https://github.com/r-hub/rhub/issues/367#issuecomment-621757715

```r
rhub::check(
  env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
)
```
