### ISSUE TITLE
issue with install instruction

### ISSUE THREAD

**Issue by rlzijdeman** [IQSS/dataverse-client-r#9]
Hi, in the installation instruction it reads one should use 'ghit'.  I'm not sure what it is, but couldn't find it through google, nor does the provided code work on my Mac. The usual code does work:

library(devtools) #install first if not yet installed
install_github("iqss/dataverse-client-r")
library("dataverse")

**Comment by leeper** [comment]
@rlzijdeman  ghit is a lightweight alternative package to devtools for installing from GitHub. It is on CRAN. What error did you receive when you tried to install using the supplied instructions?

**Comment by rlzijdeman** [comment]
Hi, the initial error I received was:
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ghit’

However, in hindsight I was on a bad connection yesterday, so maybe that was the cause of the issue.

This morning I tried again, and it now seems to download, but with the following error:
Loading required package: ghit
Error : object ‘remote_ls’ is not exported by 'namespace:git2r'
trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.2/ghit_0.2.5.tgz'
Content type 'application/x-gzip' length 16163 bytes (15 KB)
==================================================
downloaded 15 KB

I hope this helps.

Best,

Richard



--
Dr. R.L. Zijdeman | CDO | International Institute of Social History | Cruquiusweg 31 | 1019 AT Amsterdam | +31 20 668 5 866

“We don’t care about the distinction between past and present, we’re going to connect them anyway”  — Prof. dr. Diego Ramiro-Fariñas #ESSHC2016

On 07 Apr 2016, at 14:14, Thomas J. Leeper <notifications@github.com<mailto:notifications@github.com>> wrote:


@rlzijdeman<https://github.com/rlzijdeman> ghit is a lightweight alternative package to devtools for installing from GitHub. It is on CRAN. What error did you receive when you tried to install using the supplied instructions?

**Comment by leeper** [comment]
@rlzijdeman Thanks. You have an outdated version of the git2r package. Running `update.packages()` will solve that issue.

**Comment by rlzijdeman** [comment]
:-( yikes… sorry… thanks for providing that feedback.
--
Dr. R.L. Zijdeman | CDO | International Institute of Social History | Cruquiusweg 31 | 1019 AT Amsterdam | +31 20 668 5 866

“We don’t care about the distinction between past and present, we’re going to connect them anyway”  — Prof. dr. Diego Ramiro-Fariñas #ESSHC2016

On 08 Apr 2016, at 14:09, Thomas J. Leeper <notifications@github.com<mailto:notifications@github.com>> wrote:


@rlzijdeman<https://github.com/rlzijdeman> Thanks. You have an outdated version of the git2r package. Running update.packages() will solve that issue.

**Comment by leeper** [comment]
@rlzijdeman No problem! Thanks for raising the issue.
