### ISSUE TITLE
switch back from `\donttest{}` to `\dontrun{}`

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#92]
*from @kuriwaki in https://github.com/IQSS/dataverse-client-r/commit/f88a01c34a1bb8673208ae49120de7d5225b8a1d#commitcomment-47749130*

> @wibeasley - studying the Rhub Solaris error, I see that the problematic `"donttest{"` call is used only once in the entire package (where the example error occurs), whereas `"dontrun{"` is used dozens of times. Is this intentional?
> 
> Seems the `"\donttest"` part all ran in the tests, and only in Solaris was there a problem.  Since R 4.0.0, `R CMD check --as-cran` runs `\donttest` examples by default. (https://community.rstudio.com/t/r-cmd-check-r-4-0-0-now-runs-donttest-how-to-proceed-with-long-running-examples/64493/3)

------------

@kuriwaki, looks like you're right again.  I'm sure I had a reason to change it the first time.  Maybe I was looking at the first segment instead of the second?

from https://r-pkgs.org/r-cmd-check.html?q=donttest#documentation
>Checking examples. Every documentation example must run without errors, and must not take too long. Exclude failing or slow tests with \donttest{}. See documenting functions for more details.

from https://r-pkgs.org/man.html?q=donttest#man-functions
> For the purpose of illustration, it’s often useful to include code that causes an error. \dontrun{} allows you to include code in the example that is not run. (You used to be able to use \donttest{} for a similar purpose, but it’s no longer recommended because it actually is tested.)

I think my real motivation was an unsuccessful attempt to have the output included in the pkgdown website, but not be a potential point of failure for CRAN.  [My next commit](https://github.com/IQSS/dataverse-client-r/commit/ba7ce1c8567ba75441093cdb5f69be6458c2f27b) was to update the site.

It's frustrating that all these pass on our local Ubuntu, Windows, & Mac machines (and Travis & win-builder), but fail on a subset of CRAN builds.  Looking at the CRAN errors again, I think you're totally right  that this is the problem because it was complaining about the [pillar](https://CRAN.R-project.org/package=pillar) package (and later its dependency the [utf8](https://CRAN.R-project.org/package=utf8) package). The colored text in the screenshot below is formatted by pillar by readr when converting the csv to a data.frame.

![image](https://user-images.githubusercontent.com/1372890/109823969-045c4e80-7bfe-11eb-8a7a-214a3712fc5f.png)

**Comment by wibeasley** [comment]
Changing this change doesn't eliminate the problems on r-hub if the package dependency is needed by the vignettes. 
https://builder.r-hub.io/status/dataverse_0.3.6.tar.gz-479a0cbd90164faba6988884ffea0e36

Here's an error thrown because [utf8](https://cran.r-project.org/web/checks/check_results_utf8.html) is currently broken on the two windows cran builds.  This dependency is so deep within the tidyverse packages (I think it's a 3rd layer dependency from dataverse) that it's gotta be causing a lot of problems for a lot of packages.  I imagine it will be fixed soon.

![image](https://user-images.githubusercontent.com/1372890/109833035-8cdeed00-7c06-11eb-858e-85d2d190df78.png)

**Comment by kuriwaki** [comment]
Thanks for this explanation. My vignettes still compile on local if  `%\VignetteEncoding{UTF-8}` is removed, but I see other packages have that so maybe best not to fiddle with that.

**Comment by wibeasley** [comment]
Yea, and fwiw, I don't think the utf8 package is related to the vignette syntax `%\VignetteEncoding{UTF-8}`.
