### ISSUE TITLE
GET by file DOI errors out on demo dataset

### ISSUE THREAD

**Issue by kuriwaki** [IQSS/dataverse-client-r#94]
In our demo [datafile](https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/HXJVJU/SA3Z2V&version=4.0) which we have been testing against from the beginning, calling by DOI errors out (even though calling by name works fine). Another dataset on the Harvard succeeds regardless.

``` r
library(dataverse)
library(tibble)
packageVersion("dataverse")
#> [1] '0.3.7'


# Try to Read demo dataset by DOI
get_dataframe_by_doi(
  filedoi  = "doi:10.70122/FK2/HXJVJU/SA3Z2V", 
  original = TRUE,
  .f       = readr::read_csv,
  server = "demo.dataverse.org"
)
#> Error in get_file_by_id(fileid = fileid[i], dataset = dataset, format = format, : Not Found (HTTP 404). Failed to API endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org..

# read the same file by name
get_dataframe_by_name(
  filename  = "roster-bulls-1996.tab", 
  dataset  = "doi:10.70122/FK2/HXJVJU",
  original = TRUE,
  .f       = readr::read_csv,
  server = "demo.dataverse.org"
) %>% dim()
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   number = col_double(),
#>   player = col_character(),
#>   position = col_character(),
#>   height = col_character(),
#>   weight = col_double(),
#>   dob = col_character(),
#>   country_birth = col_character(),
#>   experience_years = col_double(),
#>   college = col_character()
#> )
#> [1] 15  9


# Different datafile with file-level DOI
get_dataframe_by_doi(
  filedoi  = "doi:10.7910/DVN/ARKOTI/QJTSWV", 
  original = TRUE,
  .f       = haven::read_dta,
  server = "dataverse.harvard.edu"
) %>% dim()
#> [1] 60 10

# same but by name
get_dataframe_by_name(
  filename  = "comprehensiveJapanEnergy.tab", 
  dataset  = "doi:10.7910/DVN/ARKOTI",
  original = TRUE,
  .f       = haven::read_dta,
  server = "dataverse.harvard.edu"
) %>% dim()
#> [1] 60 10
```

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The error occurs in the core httr GET function. Here is the request URL for the one that doesn't work:

https://demo.dataverse.org/api/access/datafile/:persistentId/?persistentId=doi%3A10.70122%2FFK2%2FHXJVJU%2FSA3Z2V&format=original

and here is the request URL for the other dataset that does work:

https://dataverse.harvard.edu/api/access/datafile/:persistentId/?persistentId=doi%3A10.7910%2FDVN%2FARKOTI%2FQJTSWV&format=original

@djbrooke do you notice anything different about the URLs (or something obviously wrong with the former?)

**Comment by qqmyers** [comment]
It looks like removing the final / before the ? resolves the issue on demo.dataverse.

**Comment by Danny-dK** [comment]
Does this have to do with a doi in itself not being resolvable on demo dataverses? Publication on demo dataverses don't get resolvable doi's, so if it doesn't resolve, the get_dataframe_by_doi won't know where to look? I'm assuming this won't work on other datasets in demo dataverses (I tried it with my own test dataverses in demo.dataverse.nl?

**Comment by qqmyers** [comment]
The Dataverse APIs that allow :persistentId as an option don't try to resolve the DOI at DataCite, so they should work fine with fake/unresolvable DOIs.

**Comment by Danny-dK** [comment]
Ah I see. Well, I'm sure all of you know this, but if in Rstudio you hold ctrl and click on a function you'll 'dive' into that function. Do this for ```get_dataframe_by_doi()```, consequently for ```get_dataframe_by_id()```, then for ```get_file()```, then for ```get_file_by_id()```. At the bottom it lists:

```
 if (use_persistent_id) {
    u_part <- "access/datafile/:persistentId/?persistentId="
  }
  else if (format == "bundle") {
    u_part <- "access/datafile/bundle/"
  }
  else if (format == "original") {
    u_part <- "access/datafile/"
  }
  else {
    stop("The `format` value should be 'bundle' or 'original', or a doi needs to be passed to `fileid`.")
  }
  u <- paste0(api_url(server), u_part, fileid)
  r <- httr::GET(u, httr::add_headers(`X-Dataverse-key` = key), 
    query = query, ...)
  httr::stop_for_status(r)
  httr::content(r, as = "raw")
}
```

If I just select the server, u-part, fileid, and run the httr::GET() it works on your suggestion to remove the forward slash at the ? sign for both dataverses (demo and harvard).

```
# demo.dataverse.org doi

server <- 'demo.dataverse.org'
u_part1 <- "access/datafile/:persistentId/?persistentId="
u_part2 <- "access/datafile/:persistentId?persistentId="
fileid <- "doi:10.70122/FK2/HXJVJU/SA3Z2V"

u1 <- paste0(dataverse:::api_url(server), u_part1, fileid)
u2 <- paste0(dataverse:::api_url(server), u_part2, fileid)
 
# Only the second one with the forward slash removed will run. The first one will get the 404 error.
 
r <- httr::GET(u1)
r2 <- httr::GET(u2)


# dataverse.harvard.edu doi

server <- 'dataverse.harvard.edu'
u_part1 <- "access/datafile/:persistentId/?persistentId="
u_part2 <- "access/datafile/:persistentId?persistentId="
fileid <- "doi:10.7910/DVN/ARKOTI/QJTSWV"

u1 <- paste0(dataverse:::api_url(server), u_part1, fileid)
u2 <- paste0(dataverse:::api_url(server), u_part2, fileid)
 
# Both lines will run. 

r <- httr::GET(u1)
r2 <- httr::GET(u2)

```

So considering both lines will run in the dataverse.harvard.edu example and only the second line in the demo.dataverse.org example, one could just adjust the ``` u_part <- "access/datafile/:persistentId/?persistentId="``` in the original code to remove the forward slash just before the ? sign. But I'm not that familiar with these functions or whether it breaks something else.

**Comment by landreev** [comment]
So yes, we broke the notation with the trailing slash (`access/datafile/:persistentId/?persistentId=...`) in v5.4. Which of course is a problem, since this is how it's documented in the guide, unfortunately.
I have made a fix (https://github.com/IQSS/dataverse/pull/7789), and we are planning to release it as v5.4.1. (So the plan is for Harvard prod. Dataverse to go from v5.3 to v5.4.1 directly).

**Comment by kuriwaki** [comment]
@qqmyers  @landreev. Thank you, it all makes sense now. 

Can v5.3 (the old one) accept URLs *without* the backslash? That seems to be the case in the Harvard dataverse datafile above. If so, we can just hard-code the removal of the backslash in all our calls. 

If not, we'll need to check the [version number](https://dataverse.harvard.edu/api/access/datafile/:persistentId/?persistentId=doi%3A10.7910%2FDVN%2FARKOTI%2FQJTSWV&format=original) of the Dataverse for a given `server` value, and then remove based on `version >= 5.4.1`.

**Comment by kuriwaki** [comment]
I removed the backslash from all calls in PR #95, and so far I don't see a problem in any of our unit tests.

**Comment by landreev** [comment]
> @qqmyers @landreev. Thank you, it all makes sense now.
> 
> Can v5.3 (the old one) accept URLs _without_ the backslash? 

Yes, the notation without the backslash is supported in all versions, past and future. 
We consider it to be the recommended form (in fact, all of our automated tests call the API without this trailing backslash - so that's why we hadn't noticed it, until you reported the issue). 
But, as I mentioned earlier, we realized that the API guide has it documented _with_ the backslash... So, even if you make this change in your code, we definitely want to have it fixed in future releases - because other people are likely using that notation too.

**Comment by kuriwaki** [comment]
@landreev I definitely followed that section of the API guide when I wrote this part of the package. So, that's good to know. 

@wibeasley the PR should fix most if not all the [CRAN errors](https://cran.r-project.org/web/checks/check_results_dataverse.html), although there may be places other than `get_file` that may fail due to the same issue.

**Comment by landreev** [comment]
Thank you for reporting it. I'm glad you noticed before we had a chance to deploy it in production.
