### ISSUE TITLE
Remove server tests from daily CRAN builds

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse-client-r#96]
I think we can't rely on CRAN to test the package, and instead we'll need to regularly test on non-CRAN infrastructure.  @pdurbin has suggested something like Jenkins (#22), and we should probably do more with [GitHub Actions](https://github.com/IQSS/dataverse-client-r/actions) to run tests regularly (eg, weekly or daily) instead of just when there's a commit.  I don't think we'll be able to cover the breadth of OSes that CRAN covers, but we should be able to get the major ones (eg, the last two Ubuntu LTSes) and forget about ones like Solaris.

Even though @kuriwaki, @landreev, and others solved #94 & #95, I don't think this will be the last one ever.  As you can see in Ripley's warning below, we may not get another chance.

CRAN will still perform the typical RCMD checks daily, but only a subset of the [testthat tests](https://github.com/IQSS/dataverse-client-r/tree/master/tests/testthat).  Specifically, [`testthat::skip_on_cran()`](https://testthat.r-lib.org/reference/skip.html) will be added to any test that relies on an external computer like demo.dataverse.org.

@pdurbin, @kuriwaki, or anyone else ...any comments? @pdurbin, you've mentioned before how continual testing with Jenkins can improve both the R package and stability of dataverse server code.  Tell us how we can help put it on Jenkins (in #22) if that' still your suggestion.

On 07/04/2021 07:19, Prof Brian Ripley wrote:
> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_dataverse.html>.
>
> Please correct before 2021-04-21 to safely retain your package on CRAN.
>
> It seems we need to remind you of the CRAN policy:
>
> 'Packages which use Internet resources should fail gracefully with an informative message
> if the resource is not available or has changed (and not give a check warning nor error).'
>
> This needs correction whether or not the resource recovers.
>
> This is the third notification already in 2021.  Please do comply with
the policy -- there will be no further notifications.

**Comment by kuriwaki** [comment]
Moving to do daily builds on ghactions sounds like a good course of action. The PR looks thorough!
